nh_exercice_homepage:
    path:     /
    defaults:
        { _controller: NHExerciceBundle:Default:index }

nh_exercice_new:
    path:     /formulaire
    defaults:
        { _controller: NHExerciceBundle:Default:formulaire }

nh_exercice_valid:
    path:    /valid
    defaults:
        { _controller: NHExerciceBundle:Default:valid }

