nh_exercice_homepage:
    path:     /
    defaults:
        { _controller: NHExerciceBundle:Default:index }

nh_exercice_formulaire:
    path:     /formulaire
    defaults:
        { _controller: NHExerciceBundle:Default:formulaire }

nh_exercice_valid:
    path:    /valid
    defaults:
        { _controller: NHExerciceBundle:Default:valid }

nh_exercice_edit:
    path:    /edit/{id}
    defaults:
        _controller: NHExerciceBundle:Default:edit
    requirements:
        id: \d+
