nh_exercice_homepage:
    path:     /
    defaults:
        { _controller: NHExerciceBundle:Default:index }

nh_exercice_add:
    path:     /add
    defaults:
        { _controller: NHExerciceBundle:Default:add }

nh_exercice_valid:
    path:    /valid
    defaults:
        { _controller: NHExerciceBundle:Default:valid }

nh_exercice_delete:
    path:    /delete/{id}
    defaults:
        { _controller: NHExerciceBundle:Default:delete }

nh_exercice_edit:
    path:    /edit/{id}
    defaults:
        { _controller: NHExerciceBundle:Default:edit }